# Generated by Django 2.1.3 on 2019-02-12 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabbithole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=250)),
                ('hyperlink', models.CharField(max_length=250)),
                ('subscribers', models.CharField(max_length=250)),
                ('viewcount', models.CharField(max_length=250)),
                ('upload', models.CharField(max_length=250)),
                ('preview', models.CharField(max_length=1000)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rabbithole.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_name', models.CharField(max_length=250)),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rabbithole.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='channel',
            name='subcat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rabbithole.SubCategory'),
        ),
    ]
