# Generated by Django 2.1.3 on 2019-02-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbithole', '0002_auto_20190211_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='cat_name',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='subcat_name',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='cat_name',
        ),
    ]
