# Generated by Django 2.1.3 on 2019-03-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbithole', '0003_auto_20190211_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_submission', models.CharField(max_length=200)),
            ],
        ),
    ]
