# Generated by Django 2.1.3 on 2019-03-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbithole', '0004_cat_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_cat_submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_submission', models.CharField(max_length=200)),
            ],
        ),
    ]
