# Generated by Django 2.1.3 on 2019-03-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbithole', '0005_sub_cat_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='channel_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=250)),
                ('upload', models.CharField(max_length=250)),
                ('subscribers', models.CharField(max_length=250)),
                ('viewcount', models.CharField(max_length=250)),
                ('upvotes', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
