# Generated by Django 2.1.3 on 2019-03-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbithole', '0008_channel_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='channel_submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_submission', models.CharField(default='null', max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='channel',
            name='channel',
        ),
    ]
