# Generated by Django 2.1.3 on 2019-03-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbithole', '0010_auto_20190318_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='channel',
            name='customUrl',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='channel',
            name='thumbnail',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='channel',
            name='uploads',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='channel',
            name='cat',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='channel',
            name='sub_cat',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='channel',
            name='subscribers',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='channel',
            name='viewcount',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='channel_submissions',
            name='channel_submission',
            field=models.CharField(max_length=200),
        ),
    ]
